FROM unidata/tdm-docker:5.6
COPY ./content/ /usr/local/tomcat/content/tdm/thredds/

# correct permission issue on /data/TDSIndexFiles/data/rda/data
RUN mkdir -p /data/TDSIndexFiles/data/rda/data
RUN chmod 777 /data/TDSIndexFiles/data/rda/data

# Source env file in helmchart?
    #env_file:
    #- "compose${THREDDS_COMPOSE_ENV_LOCAL}.env"
