version: '3'

services:

  nginx:
    build: . 
    ports:
      #- "8080:80"
      - "443:443"
    #expose:
    #  - '443'
    container_name: nginx
    volumes:
      - /gpfs/csfs1/collections/rda/data:/gpfs/csfs1/collections/rda/data
      - /gpfs/csfs1/collections/rda/transfer:/gpfs/csfs1/collections/rda/transfer
      - /etc/letsencrypt/live/rda-tds.ucar.edu/:/etc/letsencrypt/live/rda-tds.ucar.edu/
      - /etc/letsencrypt/archive/rda-tds.ucar.edu:/etc/letsencrypt/archive/rda-tds.ucar.edu
      - /data/rda/data/:/data/rda/data
      - /data/logs/nginx/:/var/log/nginx/
    env_file:
      - "compose.env"

  thredds-production:
    image: unidata/thredds-docker:5.6
    ports:
      - "8443:8443"
    container_name: thredds
    hostname: tds-host
    volumes:
      - /data/logs/tomcat:/usr/local/tomcat/logs
      - ./content/thredds/logs/:/usr/local/tomcat/content/thredds/logs/
      - ./conf/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
      - ./conf/server.xml:/usr/local/tomcat/conf/server.xml
      - ./conf/cert.pem:/usr/local/tomcat/conf/cert.pem
      - ./conf/chain.pem:/usr/local/tomcat/conf/chain.pem
      - ./conf/privkey.pem:/usr/local/tomcat/conf/privkey.pem
      #- /etc/letsencrypt/live/rda-tds.ucar.edu/:/etc/letsencrypt/live/rda-tds.ucar.edu/
      #- /etc/letsencrypt/archive/rda-tds.ucar.edu/:/etc/letsencrypt/archive/rda-tds.ucar.edu/
      - ./content/thredds:/usr/local/tomcat/content/thredds
      - /gpfs/csfs1/collections/rda/data:/gpfs/csfs1/collections/rda/data
      - /data/rda/data/:/data/rda/data
      - /data/TDSIndexFiles:/data/TDSIndexFiles
    env_file:
      - "compose${THREDDS_COMPOSE_ENV_LOCAL}.env"
    healthcheck:
      test: curl --fail https://thredds.rda.ucar.edu:8443/thredds || exit 1
      interval: 60s
      timeout: 10s
      retries: 5
