apiVersion: v1
kind: Pod
metadata:
  name: log-stats-report-test
  namespace: rda
spec:
  initContainers:
  - name: init-script
    image: python:3.11-slim
    command: ["/bin/sh", "-c", "cp /configmap-scripts/log_stats.py /scripts/log_stats.py"]
    volumeMounts:
    - mountPath: /configmap-scripts
      name: configmap-volume
    - mountPath: /scripts
      name: script-volume
  containers:
  - name: log-stats
    image: python:3.11-slim
    command: ["/bin/sh", "-c", "apt-get update -qq && apt-get install -y vim && sleep infinity"]
    volumeMounts:
    - mountPath: /usr/local/tomcat/logs
      name: logs-volume
    - mountPath: /scripts
      name: script-volume
  volumes:
  - name: logs-volume
    persistentVolumeClaim:
      claimName: logs-persist
  - name: configmap-volume
    configMap:
      name: log-stats-script
  - name: script-volume
    emptyDir: {}
  restartPolicy: Never
