replicaCount: 1

webapp:
  name: rda-tds
  group: rda-tds
  path: /
  tls:
    fqdn: tds.k8s.ucar.edu
    secretName: incommon-cert-tds
  container: 
    image: docker.io/potatofever/rda-tds:sha-8a07add
    port: 8080
    memory: 12G
    cpu: 5
  volume1:
    name: campaign 
    server: gladedm1.ucar.edu
    path: /gpfs/csfs1/collections/rda/ #/gpfs/csfs1/
    readOnly: true
  volume:
    fs:
      name: tds-persist
      size: 100Gi
      mountPath: /data/TDSIndexFiles

