replicaCount: 1

webapp:
  name: rda-tds
  group: rda-tds
  path: /
  tls:
    fqdn: tds.k8s.ucar.edu
    secretName: incommon-cert-tds
  container: 
    image: potatofever/rda-tds
    port: 8080
    memory: 12G
    cpu: 5
