replicaCount: 1

webapp:
  name: rda-tds
  group: rda-tds
  path: /
  tls:
    fqdn: tds.k8s.ucar.edu
    fqdn2: tds.gdex.ucar.edu
    fqdn3: thredds.rda.ucar.edu
    secretName: incommon-cert-tds
  container: 
    image: docker.io/potatofever/rda-tds:sha-d1a4c59
    port: 8080
    memory: 32G
    cpu: 5
    responseTimeout: 180
    maxUploadSize: 30m
    env:
      THREDDS_XMX_SIZE: 28G
      THREDDS_XMS_SIZE: 5G
  logs: 
    name: rda-logs
    image: docker.io/potatofever/rda-logs:sha-3f40dca
    port: 8080
    memory: 2G
    cpu: 1
  tdm:
    name: gdex-tdm
    image: docker.io/potatofever/gdex-tdm:v1.2
    port: 8080
    memory: 10G
    cpu: 2
    env:
      TDM_XMX_SIZE: "10G"
      TDM_XMS_SIZE: "5G"
  volume1:
    name: campaign 
    server: gladedm1.ucar.edu
    path: /gpfs/csfs1/collections/rda/ 
    readOnly: true
  volume:
    fs:
      name: tds-persist
      size: 100Gi
      mountPath: /data/TDSIndexFiles/data/rda/data # /tmp2/TDSIndexFiles # /data/TDSIndexFiles
  volume2:
    fs:
      name: logs-persist
      size: 5Gi
      mountPath: /usr/local/tomcat/logs

