replicaCount: 3

webapp:
  name: rda-tds
  group: rda-tds
  path: /
  # SSL/TLS encryption for the user browser to Ingress connection
  tls:
    # Fully Qualified Domain Name (e.g.: <app-name>.k8s.ucar.edu)
    fqdn: tds.k8s.ucar.edu       
    fqdn2: tds.gdex.ucar.edu
    fqdn3: thredds.rda.ucar.edu
    # Kubernetes Secret that contains the TLS certificate
    secretName: incommon-cert-tds
  container: 
    image: docker.io/potatofever/rda-tds:sha-9af948e
    port: 8080
    memory: 38G
    cpu: 5
    responseTimeout: 180
    maxUploadSize: 30m
    limit_connections: 100  # Increased for concurrent requests
    limit_rps: 200          # Increased for page load bursts
 
    env:
      THREDDS_XMX_SIZE: 34G
      THREDDS_XMS_SIZE: 10G
  logs: 
    name: rda-logs
    image: docker.io/potatofever/rda-logs:sha-3f40dca
    port: 8080
    memory: 2G
    cpu: 1
  tdm:
    name: gdex-tdm
    image: docker.io/potatofever/gdex-tdm:sha-9af948e
    port: 8080
    memory: 6G
    cpu: 2
    env:
      TDM_XMX_SIZE: "5G"
      TDM_XMS_SIZE: "2G"
  volume1:
    name: campaign 
    server: gladedm1.ucar.edu
    path: /gpfs/csfs1/collections/rda/ 
    readOnly: true
  volume:
    fs:
      name: tds-persist
      size: 1Ti
      mountPath: /data/TDSIndexFiles/data/rda/data # /tmp2/TDSIndexFiles # /data/TDSIndexFiles
  volume2:
    fs:
      name: logs-persist
      size: 5Gi
      mountPath: /usr/local/tomcat/logs

