replicaCount: 1

webapp:
  name: rda-tds
  group: rda-tds
  path: /
  tls:
    fqdn: tds.k8s.ucar.edu
    secretName: incommon-cert-tds
  container: 
    image: docker.io/potatofever/rda-tds:sha-b07c688
    port: 8080
    memory: 12G
    cpu: 5
  logs: 
    name: rda-logs
    image: docker.io/potatofever/rda-logs:sha-12345
    port: 8080
    memory: 2G
    cpu: 1
  volume1:
    name: campaign 
    server: gladedm1.ucar.edu
    path: /gpfs/csfs1/collections/rda/ 
    readOnly: true
  volume:
    fs:
      name: tds-persist
      size: 100Gi
      mountPath: /data/TDSIndexFiles/data/rda/data # /data/TDSIndexFiles
  volume2:
    fs:
      name: logs-persist
      size: 5Gi
      mountPath: /usr/local/tomcat/logs

