apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: {{ .Values.webapp.volume.fs.name }}
    namespace: {{ .Release.Namespace}}
spec:
    accessModes:
        - ReadWriteMany
    storageClassName: mlcephfs
    resources:
        requests:
            storage: {{ .Values.webapp.volume.fs.size | default "1Gi" }} 
