apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.webapp.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    group: {{ .Values.webapp.group }}
  annotations:
    cert-manager.io/cluster-issuer: "incommon"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: "{{ .Release.Namespace }}-{{ .Values.webapp.name }}-ratelimit@kubernetescrd,{{ .Release.Namespace }}-{{ .Values.webapp.name }}-inflightreq@kubernetescrd,{{ .Release.Namespace }}-{{ .Values.webapp.name }}-buffering@kubernetescrd"
    traefik.ingress.kubernetes.io/service.serversTransport: "{{ .Release.Namespace }}-{{ .Values.webapp.name }}-transport@kubernetescrd"
spec:
  ingressClassName: {{ .Values.webapp.ingressClassName }}
  tls:
    - hosts:
      - {{ .Values.webapp.tls.fqdn }}
      - {{ .Values.webapp.tls.fqdn2 }}
      - {{ .Values.webapp.tls.fqdn3 }}
      secretName: {{ .Values.webapp.tls.secretName }}
  rules:
  - host: {{ .Values.webapp.tls.fqdn }}
    http:
      paths:
      - path: {{ .Values.webapp.path }}
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.webapp.name }}
            port:
              number: {{ .Values.webapp.container.port }}
  - host: {{ .Values.webapp.tls.fqdn2 }}
    http:
      paths:
      - path: {{ .Values.webapp.path }}
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.webapp.name }}
            port:
              number: {{ .Values.webapp.container.port }}
  - host: {{ .Values.webapp.tls.fqdn3 }}
    http:
      paths:
      - path: {{ .Values.webapp.path }}
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.webapp.name }}
            port:
              number: {{ .Values.webapp.container.port }}
