apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: {{ .Values.webapp.tdsPersist.fs.name }}
    namespace: {{ .Release.Namespace}}
    annotations:
        argocd.argoproj.io/sync-options: Prune=false
spec:
    accessModes:
        - ReadWriteMany
    storageClassName: cephfs
    resources:
        requests:
            storage: {{ .Values.webapp.tdsPersist.fs.size | default "1Gi" }}
