replicaCount: 3
revisionHistoryCount: 9

webapp:
  name: rda-tds-dev
  group: rda-tds-dev
  path: /
  # SSL/TLS encryption for the user browser to Ingress connection
  tls:
    # Fully Qualified Domain Name (e.g.: <app-name>.k8s.ucar.edu)
    fqdn: tds-dev.k8s.ucar.edu       
    # Kubernetes Secret that contains the TLS certificate
    secretName: incommon-cert-tds-dev
  ingress:
    # Ingress class to use (e.g., nginx, traefik, etc.)
    className: traefik-external
  container: 
    # load_balance: ewma  # Enable weighted load balancing to avoid traffic concentrate on a subset of pods 
    image: docker.io/potatofever/rda-tds:sha-739e830
    port: 8080
    memory: 40G
    cpu: 5
    ephemeralStorageLimit: 5Gi
    responseTimeout: 180
    maxUploadBytes: 31457280  # 30m in bytes for Traefik buffering middleware
    limit_connections: 10
    limit_rps: 5
    limit_rps_burst: 10
 
    env:
      THREDDS_XMX_SIZE: 32G
      THREDDS_XMS_SIZE: 10G
  logs: 
    name: rda-dev-logs
    image: docker.io/potatofever/rda-logs:sha-3f40dca
    port: 8080
    memory: 2G
    cpu: 1
    ephemeralStorageLimit: 1Gi
  tdm:
    name: gdex-dev-tdm
    image: docker.io/potatofever/gdex-tdm:sha-4f85cd4
    port: 8080
    memory: 6G
    cpu: 2
    ephemeralStorageLimit: 2Gi
    env:
      TDM_XMX_SIZE: "5G"
      TDM_XMS_SIZE: "2G"
  volume1:
    name: campaign
    server: gladedm1.ucar.edu
    path: /glade/campaign/collections/gdex/
    readOnly: true
  volume:
    fs:
      name: tds-dev-persist
      size: 1Ti
      mountPath: /data/TDSIndexFiles/data/rda/data # /tmp2/TDSIndexFiles # /data/TDSIndexFiles
  volume2:
    fs:
      name: logs-dev-persist
      size: 50Gi
      mountPath: /usr/local/tomcat/logs

