# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Publish logs image

on:
  push:
    paths:
      - rda-tds/Dockerfile-logs
jobs:
  push_to_registry:
    name: Push logs image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
      attestations: write
      id-token: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Change to working directory
        run: cd rda-tds

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: potatofever/rda-logs
          tags: |
            type=schedule,pattern={{date 'YYYYMMDD-HHmm'}}
            type=sha

      - name: Build and push Logs Docker image
        id: push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: "{{defaultContext}}:rda-tds"
          file: ./Dockerfile-logs
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Set Timestamp
        id: timestamp
        run: |
          echo "datetime=$(date)" >> $GITHUB_OUTPUT

      - name: Update helm chart
        run: |
          echo "current path is `pwd`"
          echo "${{ steps.meta.outputs.tags }}"
          sed -i "s/rda-logs\:.*/rda-logs`echo ${{ steps.meta.outputs.tags }}| grep -o ':.*'`/" rda-tds-helm/values.yaml
          
      - name: Create Pull Request
        id: pr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update logs Docker image tag - ${{ steps.timestamp.outputs.datetime }}"
          committer: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
          author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
          branch: "update-logs-image"
          branch-suffix: timestamp
          delete-branch: true
          title: "🐳 Update logs Docker image tag - ${{ steps.timestamp.outputs.datetime }}"
          body: |
            ## Logs Docker Image Update
            
            **Time:** ${{ steps.timestamp.outputs.datetime }}
            **Run ID:** ${{ github.run_id }}
            **New Tags:** ${{ steps.meta.outputs.tags }}
            **Trigger:** Dockerfile-logs was modified
            **Action:** Updated Helm chart with new image tag
            
            This PR will automatically merge to deploy the updated logs image.
            
            ---
            *This PR was created automatically by the logs deployment workflow.*
          base: main
          draft: false
          
      - name: Auto-merge Pull Request
        if: steps.pr.outputs.pull-request-number
        run: |
          # Wait a moment for PR to be fully created
          sleep 1m
          
          # Auto-merge the PR
          gh pr merge ${{ steps.pr.outputs.pull-request-number }} \
            --auto \
            --squash \
            --subject "Update logs Docker image tag - ${{ steps.timestamp.outputs.datetime }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}


